### ISSUE TITLE
convert_to_text should remove html comments and style blocks

### ISSUE THREAD

**Issue by warp** [premailer/premailer#110]
Microsoft office embeds some VML styles between conditional comments

```
<!--[if !mso]><style>v\:* {behavior:url(#default#VML);}
o\:* {behavior:url(#default#VML);}
w\:* {behavior:url(#default#VML);}
.shape {behavior:url(#default#VML);}
</style><![endif]-->
```

These should be stripped from text output

**Comment by rutfin** [comment]
Premailer should preserve MSO conditional (). Currently conditionals are treated as a comment an are removed from the email.
Is there any update about this issue?
