### ISSUE TITLE
Style tag being moved to end of body tag instead of remaining in head tag (Breaks Outlook)

### ISSUE THREAD

**Issue by danlance** [premailer/premailer#141]
We have just migrated our email marketing application to new servers - and as such have installed the latest version of premailer using Gem.

Prior to migration, premailer was correctly keeping the style block for styles which cannot be applied directly within the header tag - now it is being moved to the bottom of the body tag.

Whilst this is not a problem for web browsers (and may not technically be incorrect according to standards), the styles in this block are then ignored in Outlook 2007+

I am calling Premailer from the command line using the following ruby script, passing input and output file paths as arguments:

``` ruby
require 'rubygems'
require 'Premailer'   #Reference Premailer GEM
inputfile = ARGV[0]   #1st argument = location of source file (must be / not \)  
outputfile = ARGV[1]  #2nd argument = location of file to write output to
premailer = Premailer.new(inputfile, :warn_level => Premailer::Warnings::SAFE)  #Call premailer, passing input file location

# Write the HTML output to output file location
fout = File.open(outputfile, "w")
fout.puts premailer.to_inline_css
fout.close
```
# Examples:
- _Input_: http://pastebin.com/kb5N0E8s
- _Output_: http://pastebin.com/Pr05Ypyt
# Configuration:
## Previous:

```
ruby 1.9.1p378 (2010-01-10 revision 26273) [i386-mingw32]

*** LOCAL GEMS ***

css_parser (1.0.1)
hpricot (0.8.2)
htmlentities (4.2.1)
premailer (1.5.4)
text-hyphen (1.0.0)
text-reform (0.2.0)
```
## Current:

```
ruby 1.9.3p194 (2012-04-20) [i386-mingw32]

*** LOCAL GEMS ***

addressable (2.3.2)
bigdecimal (1.1.0)
css_parser (1.2.6)
hpricot (0.8.6)
htmlentities (4.3.1)
io-console (0.3)
json (1.7.5)
minitest (2.5.1)
premailer (1.7.3)
rake (0.9.2.2)
rdoc (3.9.4)
```

Is this a bug - or is there a configuration argument etc. which I can use to revert to the previous behaviour?

**Comment by akzhan** [comment]
Fixed a time ago.
