### ISSUE TITLE
Fails to handle left curly bracket in CSS content - content:'{' 

### ISSUE THREAD

**Issue by ProBackup-nl** [premailer/premailer#170]
When CSS contains ```content:'{'````the results are incorrect.

Current workaround is to unicode escape this left curly brace content in the source CSS by replacing ```content:'{';``` with ```content:'\007b';```

**Comment by scouttyg** [comment]
Think this should now be solved from this: https://github.com/premailer/css_parser/pull/61. Should also handle other content fixes (quotes, backslashes, etc)

**Comment by grosser** [comment]
can be solved by updating to css_parser v1.3.7
