### ISSUE TITLE
url all my "&" change to "&amp;"

### ISSUE THREAD

**Issue by marioenriquemuo** [premailer/premailer#174]
By default the ink inliner, dosen't respect href attributes, so when I use utm_ query string parameter on my links all my "&" change to "&". This not only destroys mi tracking on google analytics or any other parameter but also it render useless all my links, destroying my campaign.

?utm_source=newsletter&utm_medium=email

**Comment by nolman** [comment]
The source of the bug is libxml2 usage in nokogiri https://github.com/sparklemotion/nokogiri/issues/1127

Basically [ampersands are not valid in xml](http://www.w3.org/TR/REC-xml/#syntax) and nokogiri uses libxml2 which follows the xml spec and escapes ampersands.
