### ISSUE TITLE
Premailer inserting <![CDATA[ on <script> tags

### ISSUE THREAD

**Issue by Saturn2888** [premailer/premailer#199]
For some reason, my script tag has a `<![CDATA[` in front of it which causes the script to not execute when `--preserve_scripts` is enabled.

Example:
```
<script runat="server">
Platform.Load('Core','1');
</script>
```
becomes
```
<script runat="server">
<![CDATA[Platform.Load('Core','1');
</script>
```

**Comment by joshjordan** [comment]
@akzhan it looks like this can be closed, yeah?

**Comment by akzhan** [comment]
ok
