### ISSUE TITLE
nokogiri wraps to_inline_css in html tag.  hpricot does not.

### ISSUE THREAD

**Issue by kwerle** [premailer/premailer#209]
I recently removed both these gems from a project that needed neither.  Except that it turns out premailer requires at least one.  I put nokogiri back in and premailer behaved differently.  After banging my head for a while (I'd changed a bunch of gems), I replaced nokogiri with hpricot and I was back to the expected behavior.

As it turns out, I need the without html tag behavior.  I'd like to see them both behave the same way, though, and wrapping html with an HTML tag seems pretty easy.  Easier than stripping the tag if you don't need it.

At the very least, there needs to be some kind of warning if they are going to behave differently.

**Comment by akzhan** [comment]
[Hpricot is over](https://github.com/hpricot/hpricot).
