### ISSUE TITLE
can't install premailer with bundler from git repo

### ISSUE THREAD

**Issue by dingsdax** [premailer/premailer#218]
i wan't to use the current master from premailer in a rails 4.0 app on ruby 2.1.0
i included the gem with:

```
gem 'premailer', :github => 'premailer'
```

or

```
gem 'premailer', :git => "git://github.com/premailer/premailer.git"
```

i tried several combinations with :refs and :branch too. 

```
bundle install
```

and 

```
bundle update premailer
```

worked as expected, but when I try to require premailer with in the app with

```
require 'premailer'
```

i get a **LoadError: cannot load such file -- premailer**

installing premailer from rubygems works fine. 

thx for the help in advance!

**Comment by visnup** [comment]
This has regressed after un-renaming from a dotfile.
