### ISSUE TITLE
Adding schema.org markup to e-mails.

### ISSUE THREAD

**Issue by tristandunn** [premailer/premailer#222]
In attempting to [add actions to e-mails](https://developers.google.com/gmail/actions/) I noticed the premailer `remove_scripts` option is `true` by default. But actionmailer_inline_css doesn't support passing custom options to premailer.

I'd like to patch one of the libraries to allow it, but unclear on which I should do:

* Disable removal of `application/ld+json` scripts in premailer.
* Support passing custom options to premailer from actionmailer_inline_css.
* Or both, with support for customizing the premailer removal query via configuration.

-------

This is a duplicate of premailer/actionmailer_inline_css#22 since it appears I should have opened it here based on activity. Feel free to close either depending on where this should be implemented.

**Comment by mleglise** [comment]
+1

**Comment by mleglise** [comment]
If using the [premailer-rails](https://github.com/fphilipe/premailer-rails) gem, add this to an initializer (such as `config/initializers/premailer_rails.rb`):

```ruby
Premailer::Rails.config.merge!({ remove_scripts: false })
```

**Comment by tristandunn** [comment]
Enabling scripts completely might not be the best solution, but with that option and the Microdata format option mentioned in premailer/actionmailer_inline_css#22 I'm going to close this.
