### ISSUE TITLE
Trigger to Keep Styles in Head <style> Tag?

### ISSUE THREAD

**Issue by kgrote** [premailer/premailer#226]
Does Premailer  have a way to force certain styles to be output directly into the head `<style>` tag rather than inline? For example, I want to define a link hover color for clients that support it:

`a:hover { color: #ff0000 !important; }`

But in order for that to work it needs to be printed in the head `<style>` tag. Right now Premailer is just ignoring it altogether. I know I can set the `preserve_styles` option and hard-code the styles into the document, but it would be great if Premailer did it dynamically so I could use SASS.

If it's not already an option, maybe a trigger class could be used to let Premailer know when to place the styles in the document head:

```
.premailer-head,
a:hover {
    color: #ff0000 !important;
}

```

**Comment by sunny** [comment]
Something else you can do is include your full style sheet in style tags:

```rb
<style><%= Rails.application.assets.find_asset('email').to_s.html_safe %></style>
```

Worked for me!

**Comment by hollensteiner** [comment]
I second that. Would be very useful!

**Comment by akzhan** [comment]
Fixed a time ago.
