### ISSUE TITLE
Premailer on JRuby

### ISSUE THREAD

**Issue by r-shah** [premailer/premailer#235]
We are interested in running premailer on JRuby. Does current version 1.8.2 support JRuby? Are there any active development going on for supporting it? Are there known area or issues with JRuby? We are willing to contribute for its support if you can let use know the issues.

**Comment by akzhan** [comment]
@r-shah Тщ active development in progrress, but codebase looks like very easy to update to jRuby.

So Prs are мукн apprepriated.

Simply try to run

```bash
bundle exec rspec
```

**Comment by r-shah** [comment]
@akzhan, @alexdunae, I have build java wrapper on top of your premailer. I have used recent version 1.8.3.
