### ISSUE TITLE
Premailer API Beta - HTML file with style tag in head doesn't work with API

### ISSUE THREAD

**Issue by Matrixian** [premailer/premailer#253]
Since last week the API based premailer does not work and we need to use the web based premailer manually to process emails.

Here ist the link for the  sample html file and results from the API call / website:
https://drive.google.com/file/d/0B-J-s96E-CfnX2tESzlGS2dTaVE/view?usp=sharing

The issue first appears when adding a style tag in the head element.

**Comment by lbineau** [comment]
For me for the same file, sometimes it works, sometimes not, that really weird.
Any idea of why ?

**Comment by akzhan** [comment]
API down.
