### ISSUE TITLE
<style> import different on windows and mac

### ISSUE THREAD

**Issue by di5abled** [premailer/premailer#256]
when premailer is importing styles it locates the style tag into the header on my windows machine and after the body tag in the mac machine of my colleague.

we are both using the newest version 1.8.4 and we use [grunt-premailer](https://github.com/dwightjack/grunt-premailer) in our workflow.

Windows:

```
<head>
    ...
    <style type="text/css">
        ...
    </style>
</head>

<body>
    ...
```

Mac: 

```
<head>
    ...
</head>

<body><style type="text/css">
    ...
</style>
```

**Comment by tjdownes** [comment]
I'm actually seeing the same result, style tag inside the body tag, on Windows 7
