### ISSUE TITLE
Solution to big css inlining (e.g. bootstrap)

### ISSUE THREAD

**Issue by brauliobo** [premailer/premailer#264]
When using gmail, it is kind of hard to inline too much css as it clips the message (it says `[Message clipped]  View entire message`). I also had this clipping problem when inline bootstrap, which has some general selectors (like `* {box-sizing: border-box}`).

So the question is, does gmail also removes `style` tags? Is there a premailer option to use `style` tags instead of attributes?

**Comment by pratik60** [comment]
+1

**Comment by oldo** [comment]
+2

**Comment by akzhan** [comment]
See https://premailer.github.io/premailer/Premailer.html

`:preserve_style_attribute`

**Comment by akzhan** [comment]
And `:nokogiri_fast` adapter to handle big emails correctly.
