### ISSUE TITLE
Pre-mailer breaks with this simple HTML

### ISSUE THREAD

**Issue by nojacko** [premailer/premailer#273]
We've had an issue with an email causing premailer to fail. Using http://premailer.dialect.ca/ I've hacked it down to the minimal html required to make it return a "Internal server error" message. 

``` html
<html>
    <head>
        <style type="text/css">
            td { vertical-align:top;}
        </style>
    </head>
    <body>
        <table>
            <tbody>
                <tr>
                    <td style="border-bottom-width: 1px; border-color: #e6dfe0;">
                        Sad Face!
                    </td>
                </tr>
            </tbody>
        </table>
    </body>
</html>
```

Removing `vertical-align:top;`, `border-bottom-width: 1px;`, or `border-color: #e6dfe0;` allows the email to be processed.

**Comment by jontsai** [comment]
Hey @nojacko, did you try setting any of these other options:

https://github.com/premailer/premailer/wiki/Premailer-Parameters-and-Options

Like `preserve_styles`? It seems like it doesn't play nicely when you have both inline-styles and header-CSS styles

**Comment by adamlc** [comment]
@jontsai it doesn't seem to make a difference what options are set (if any)

**Comment by nojacko** [comment]
@jontsai in addition to what @adamlc said, it's that exact combination of those 3 specific CSS properties causing the issue. Removing anyone 1 of the 3 CSS properties allows this to be inlined correctly.

**Comment by ryanfaricy** [comment]
Have the same issue - disappointing and it's valid HTML. I don't have any of those CSS properties in my HTML either.

**Comment by annieclaudecote** [comment]
I think your issue is related to the hex color ending by `0` being passed to `border-color` while having a `border-bottom` set. https://github.com/premailer/css_parser/issues/68

**Comment by akzhan** [comment]
Closed because related to `css_parser`.
