### ISSUE TITLE
Character limit on premailer

### ISSUE THREAD

**Issue by Asha-D** [premailer/premailer#286]
We noticed when premailing our markup for emails that there is a character limit of 2^15 (32768 characters) We wondered if this was a deliberate design choice as it's concatenating our email significantly (strangely removing content from the middle of the email rather than the end). We've gotten around the problem by stripping all white space but there is still the potential for issues.

Looks like maybe a short (Int16) is used somewhere and that's the limiting factor?

**Comment by tuhinislam** [comment]
Is there any update regarding this?

**Comment by akzhan** [comment]
Try to change HTML engine adapter (to nokogumbo one).

**Comment by akzhan** [comment]
It's simple using code in `master` branch and by est `:nokogumbo` option with `gem install nokogumbo`.

**Comment by Asha-D** [comment]
Seems our problem was with visual studio. The preview window for variables only shows 32768 characters so we thought the text was being truncated.
