### ISSUE TITLE
Errno::EACCES: Permission denied with actionmailer_inline_css' gem

### ISSUE THREAD

**Issue by wellington1993** [premailer/premailer#291]
Only 1.79 version works. You know any way to solve this problem in latest premailer versions?
https://github.com/premailer/actionmailer_inline_css/issues/24

Thanks!

**Comment by akzhan** [comment]
Should be fixed by https://github.com/premailer/actionmailer_inline_css/commit/6879d32a3139365643796345a231a671beebd484
