### ISSUE TITLE
Why does Premailer convert ASCII code into symbols/characters?

### ISSUE THREAD

**Issue by adamt19** [premailer/premailer#30]
Premailer converts [& copy ;] (without spaces) to ©, [& quot ;] to ", [& amp ;] to &.. and I can't imagine a use case where this would be helpful. I've emailed Alex about this and I believe he told me that some people want it different ways.

I don't get it - this takes a perfectly-validated email transmission, and leaves with potentially hundreds of validation errors. 

It makes premailer no-longer a useful tool for us, and I imagine most people, at all.

WHO are the people that told Alex they needed premailer to behave like this? Are they a majority?

**Comment by akzhan** [comment]
Closed due to #181.
