### ISSUE TITLE
[QUESTION] background-image/position/repeat is replaced with background

### ISSUE THREAD

**Issue by marocas** [premailer/premailer#301]
dwightjack/grunt-premailer#40

Hello,
I've posted this question on Grunt Premailer, and the project owner asked me to place this issue/question here, like the title says, when i use backgroun-image/position/repeat, they are replaced with background.

Is there a way to make the css inline go like i have on css file?

Thank you in advance,
Mário Silva.

**Comment by akzhan** [comment]
Should be fixed by latest version
