### ISSUE TITLE
Trouble with HTML string and base_url

### ISSUE THREAD

**Issue by pbyrne** [premailer/premailer#302]
We've been using Premailer to automatically inline CSS in our outgoing emails, and that's been going really well. Yesterday I tried using the `base_url` option to convert any stray relative paths to absolute URLs. That worked, but it caused the delivered email to not have any inlined CSS.

The relevant section of our ActionMailer interceptor looks like this:

```ruby
options = { with_html_string: true, base_url: ActionMailer::Base.asset_host }
premailer = Premailer.new(html_part.body.to_s, options)
```

After some digging through the Premailer source, I tracked down the problem to [this chunk of `load_css_from_html!`](https://github.com/premailer/premailer/blob/f4ec52692435aca8c2cbbc21113f791907a21c7f/lib/premailer/premailer.rb#L298-L301).

If I turn that conditional into `if false`, everything works fine. The problem seems to be that there's no fallback to using the URL if Premailer can't load the file locally (which the other branch in that conditional does). This feels like an unintentional bug rather than an intentional difference in behavior, and that the `unless File.exists?(link_uri)` fallback to the URL should exist outside of that `else`.

**Comment by akzhan** [comment]
Thanks for the investigitation. Can you provide PR?

**Comment by eveevans** [comment]
@pbyrne Do you solve it ? 
How?
