### ISSUE TITLE
[QUESTION] Same property with diferent size units

### ISSUE THREAD

**Issue by marocas** [premailer/premailer#305]
Hello, im starting to use rem instead of px, and i found that with premailer, the style inline only goes with rem units, is there a way to have the fallback to px on the inline version, since some emails like outlook don't use rem?

Exemple:
h1{
 font-size:32px;
 font-size:3.2rem;
}

It only uses the font-size: 3.2rem, it would be good to use both.

Thanks in advance,
Mário Silva.

**Comment by akzhan** [comment]
Has been [fixed](https://github.com/premailer/css_parser/commit/7ec7c81d6b2a6496fa88edb25e2f18856c4d384c) in `css_parser` gem, but not released yet.

**Comment by akzhan** [comment]
Oops, there is another trouble. You should create issue in `css_parser`.

**Comment by marocas** [comment]
@akzhan thanks for the reply.
