### ISSUE TITLE
Requirement for Ruby  2.0

### ISSUE THREAD

**Issue by ss44** [premailer/premailer#310]
The latest premailer commit breaks compatibility with ruby <= 2.0 I'm not sure if this intentional or not, but seems like either formal support for ruby <= 2.0 should be defined in the gemfile so that bundler can still grab the correct version.

**Comment by akzhan** [comment]
Which of? `Gemfile.lock` doesn't affect functionality.

**Comment by akzhan** [comment]
And of course by #294 we said bye to old rubies.
