### ISSUE TITLE
Premailer URL encodes element attributes

### ISSUE THREAD

**Issue by sean-cherbone** [premailer/premailer#321]
I am using the Apache Lang3 StrSubstitutor  to dynamically generate emails. The work flow goes like this.
- While building the project, run premailer on some email templates
- During runtime, upon mail event:
  1. pull in the premailer inlined template
  2. replace certain parts of the email with dynamic content
  3. send the now complete email

The issue is that the premailer is URL encoding the ${} characters that the StrSubstitutor needs to recognize the token to swap out. For example &lt;a href="${some.link}"&gt; gets inlined to &lt;a href="%24%7Bsome.link%7D"&gt;. This only happens to element attributes.

**Comment by codylerum** [comment]
Seeing the same.

With an input file that has

`<a href="/reset/$token" class="btn-primary">Reset Your Account</a>`

the inlined HTML is correct like `/reset/$token`

but the to plain text renders as `/reset/%24token`

**Comment by codylerum** [comment]
It appears it does not do this with the hpricot adapter, but since that is going away it's not a great workaround.

**Comment by SirRawlins** [comment]
Found this same issue myself this morning, related to Nokogirl by the looks of it. Another comment on this related issue suggests setting a full DOCTYPE on the HTML, this seemed to solve the issue for me.

https://github.com/premailer/premailer/issues/193

**Comment by akzhan** [comment]
Solution is https://github.com/premailer/premailer/issues/193#issuecomment-97645998
