### ISSUE TITLE
`list-style-position` is changed to `list-style` when inlining CSS

### ISSUE THREAD

**Issue by egh** [premailer/premailer#327]
The following code
```ruby
Premailer.new(StringIO.new('<html><head></head><body><ol><li>hello</li></ol></body></html>'), :css_string => 'li { list-style-position: foo; }').to_inline_css
```
Generates the string:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><ol><li style="list-style: inside;">hello</li></ol></body></html>
```

Note that the css style `list-style-position: inside` has been changed to `list-style: inside`. This changes the meaning of the style and changes the rendering from an ordered list to a bullet list.

**Comment by CollinY2K** [comment]
I noticed the same thing appears to happen with other properties, in particular on `background-repeat: no-repeat;` changing to `background: no-repeat;`. In my scenario, this broke my background, as it was defined in the html `background` attribute.

**Comment by akzhan** [comment]
Looks like fixed by latest releases.

**Comment by egh** [comment]
Yes, this seems fixed. Thank you!
