### ISSUE TITLE
Support for scoped attribute

### ISSUE THREAD

**Issue by BenMorel** [premailer/premailer#331]
In HTML5, when the [scoped](http://html5doctor.com/the-scoped-attribute/) attribute is used on `<style>`, the stylesheet only applies to the parent element of the `<style>` tag, and its descendants.

Check the following example:

```
<div>
    <style scoped>
        a { color: red; }
    </style>

    <a href="">test</a>
</div>

<a href="">test</a>
```

Premailer should produce the following result:

```
<div>
    <a href="" style="color: red;">test</a>
</div>

<a href="">test</a>
```

Instead it produces:

```
<div>
    <a href="" style="color: red;">test</a>
</div>

<a href="" style="color: red;">test</a>
```

Support for this attribute would be great, especially when using partial views that contain their own stylesheets, this avoids potentially overlapping styles.

**Comment by grosser** [comment]
PR welcome ... not sure if it's easy or crazy ... but would be nice to have!

**Comment by Gyllsdorff** [comment]
I thought that attribute was deprecated?

From https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style#attr-scoped

> **Non-standard**
> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behaviour my change in the future.

> **Obsolete**
> This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.

**Comment by BenMorel** [comment]
I didn't realize that this feature is now deprecated. This is a shame, as there is currently no replacement for it ([this discussion](https://github.com/whatwg/html/issues/552) mentions custom elements / shadow DOM instead, but they do not *easily* solve the problem `<style scoped>` solved, as many comments pointed out).

I'm not sure whether premailer could support a non-standard attribute for this use case?

**Comment by meowsus** [comment]
We probably don't want to be encouraging the use of obsolete and generally discouraged features :/

Thank you for your efforts, though, @BenMorel!
