### ISSUE TITLE
Please add "source code" link to rubygems.org profile

### ISSUE THREAD

**Issue by jaredbeck** [premailer/premailer#336]
By logging into rubygems.org, you can add a "source code" link to the links section of your gem's profile page.

Here is a screenshot of the links section now, without the requested link:

![screen shot 2017-02-15 at 5 27 43 pm](https://cloud.githubusercontent.com/assets/380809/22998333/40a69670-f3a4-11e6-98f5-9414392b0f4b.png)

Thanks!

**Comment by akzhan** [comment]
Thanks. Gem links updated.

**Comment by jaredbeck** [comment]
Thanks, but I think you entered the "source code" link incorrectly. When I click the link, I tries to go to `https://github.com/premailer/premailerhttps://github.com/premailer/premailer/issues`.

**Comment by akzhan** [comment]
Thanks again, fixed.
