### ISSUE TITLE
No changelog?

### ISSUE THREAD

**Issue by volmer** [premailer/premailer#339]
Where can I read the changes for each version of the gem?

**Comment by grosser** [comment]
compare helps https://github.com/premailer/premailer/compare/v1.9.2...v1.9.3
imo it's a maintenance overhead with very little gain at least for smaller projects ... update if you want new features/bugfixes ... ideally the commit messages should be written well and serve as changelog

**Comment by volmer** [comment]
Perhaps, but changelogs are also useful to communicate upgrade instructions, deprecations, and breaking changes. It doesn't even need to be a file, as GitHub already provides a very nice [releases](https://help.github.com/articles/creating-releases/) feature that could be used to document versions. 

I find the lack of a changelog troublesome to whoever is trying to update the gem, specially for large applications where the CSS of a bunch of emails would have to be manually re-checked all the time since *anything* can happen in the next `bundle update`.

Well, my question here is answered, therefore I'm closing the issue.

**Comment by grosser** [comment]
I mostly blindly update the gems I use except Rails for our biggest apps
... also don't expect anyone to read them / trying to make changes in a way
that spits out nice deprecations.

**Comment by volmer** [comment]
> I mostly blindly update the gems I use except Rails for our biggest apps

Yes, I do that for my pet projects too, but the company I work for can't afford having a service disruption in our email service due to a breaking change blindly introduced by one of the gems we depend on.

**Comment by akzhan** [comment]
@volmer lock gem version.

And yes, I need to make version minor inc. Will do.

**Comment by akzhan** [comment]
```
➜  premailer git:(master) gem yank premailer -v 1.9.3
Yanking gem from https://rubygems.org...
Successfully deleted gem: premailer (1.9.3)
```

Will be rereleased as `1.10.0`, so please set your dependency to  `~>1.9.0` or switch to `:nokogiri_fast` adapter.

Deprecation notice exist for latest half of year.

**Comment by volmer** [comment]
@akzhan I do lock all my gem versions. But I still need to upgrade them eventually for bugfixes, compatibility, new features, etc. The lack of a changelog for Premailer makes that process very difficult, though.

**Comment by akzhan** [comment]
Ok, will do

**Comment by volmer** [comment]
@grosser For some inspiration http://keepachangelog.com
