### ISSUE TITLE
warning: URI.escape is obsolete

### ISSUE THREAD

**Issue by ioquatix** [premailer/premailer#341]
```
2.4.0/gems/premailer-1.10.0/lib/premailer/premailer.rb:445:in `rescue in block (2 levels) in convert_inline_links': warning: URI.escape is obsolete
```

**Comment by grosser** [comment]
can you make a PR to remove it ?
... make sure there is a test that show the url is still valid :)

**Comment by ioquatix** [comment]
Apparently it's replaced by `CGI.escape` but implementation is a bit different.

Discussion is here: http://blade.nagaokaut.ac.jp/cgi-bin/vframe.rb/ruby/ruby-core/29293?29179-31097

**Comment by grosser** [comment]
So do you think it's safe to swap it out ?

**Comment by ioquatix** [comment]
I'm still trying to figure that out... haven't had much time.

**Comment by akzhan** [comment]
It's safe to replace it with `Addressable::URI`, I suppose.

Just like `css_parser` codebase that depends on `addressable`.

But I have no time yet.

**Comment by akzhan** [comment]
Fixed by d135e0bf040888aba3ac67d83a901d0ce58bfd92

**Comment by ioquatix** [comment]
Thanks for this. However, is it really a good idea to load an entire gem for a single line? What's wrong with `CGI.escape` that `Addressible::URI#escape` fixes? Not saying what you did is bad, just think adding an entire dependency for a single line of code is a pretty heavy solution.

**Comment by grosser** [comment]
agreed, not a fan of this ... there should be some stdlib way of doing that
:(

**Comment by akzhan** [comment]
We already depends on `addressable` gem, because it's `css_parser` dependency.

And it is right way to handle escaping etc. (checked).

**Comment by ioquatix** [comment]
Okay awesome. Thanks for providing some reassurance.
