### ISSUE TITLE
HTML to plain text helper

### ISSUE THREAD

**Issue by lcpriest** [premailer/premailer#347]
Hi team,

I ran into some hanging issues with the [html to plaintext helper](https://github.com/premailer/premailer/blob/master/lib/premailer/html_to_plain_text.rb).

It turns out the lookahead on the link replace was freezing if the HTML was invalid (rather than throwing an error), it looks like the whitespace lookup is greedy in that particular regex.

```
txt.gsub!(/<a\s.*?href=["'](mailto:)?([^"']*)["'][^>]*>((.|\s)*?)<\/a>/i)
```
I'm not comfortable editing the regex as I'm not certain what every part of it does, but I managed to avoid the issue by moving some of the whitespace cleaning regexes up from the bottom.

```
    txt.squeeze!(" ")
    txt.gsub!(/\n[ \t]+/, "\n") # space at start of lines
    txt.gsub!(/[ \t]+\n/, "\n") # space at end of lines
```

I don't think this is the correct solution, but I thought I'd reach out for some discussion if appropriate.

**Comment by akzhan** [comment]
@lcpriest this issue already fixed by #346 and already released as 0.10.4.
