### ISSUE TITLE
please fix test failures

### ISSUE THREAD

**Issue by pravi** [premailer/premailer#352]
It seems the tests have been failing for quite some time https://travis-ci.org/premailer/premailer/builds Can these be ignored as issues with th test suite and not the library code?

**Comment by grosser** [comment]
last semi-green master seems to be https://travis-ci.org/premailer/premailer/builds/136506880
so can start from there ... maybe check out the commit and make a PR to see if it is still green ... kinda doubt it ... looks more like random failures accumulated over time

alternatively just dive in and try to fix a single issue, maybe they are all connected

**Comment by grosser** [comment]
... or simply mark all failing tests as `skip` so we get back to green and then can fix from there.

ideally use `pending { failing assertions }` so they notify when they get fixed, unless they are random failures in which case a `skip` might be best.

**Comment by akzhan** [comment]
PR's are welcomed

**Comment by meowsus** [comment]
@akzhan #370 and #378 both fix the builds. The latter also fixes a bug with scripts leaking into the text based emails too.
