### ISSUE TITLE
Premailer returns an unknown error

### ISSUE THREAD

**Issue by tuancaraballo** [premailer/premailer#367]
Hi there, 
I get this error when using premailer
**Premailer returned an unkown server error**

Sometime it works sometimes it doesn't. I tried the the example in the documentation
```
var premailer = require('premailer-api');
 
var emailTemplate = '
  <html>
    <head>
      <title>My Email</title>
      <style type="text/css">
        a { color: #336699; }
      </style>
    </head>
    <body>
      Styles inlined with
      <a href="http://premailer.dialect.ca">Premailer</a> via
      <a href="https://github.com/JedWatson/node-premailer">node-premailer</a>.
    </body>
  <html>';
 
premailer.prepare({html: emailTemplate }, function(err, email) {
  res.send(email.html);
});
```

and still get the same error, any suggestions?

Thank you in advance.

**Comment by soundasleep** [comment]
I think you've posted this on the wrong project, you probably want https://github.com/keichan34/premailer-api

**Comment by meowsus** [comment]
Agreed @soundasleep. It looks like @tuancaraballo should open an issue with on keichan34/premailer-api.
