### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by utkarsh2102** [premailer/premailer#373]
Hey,

There are a few test failures that could be found here:
https://paste.debian.net/1074953/

Requesting you to please fix them as this is needed for premailer-rails, which is needed for gitlab.

**Comment by ragesoss** [comment]
It looks like these are order-dependent failures.

Obviously, fixing the order dependency would be great. Testing with set seed is probably a quicker fix, eg, `bundle exec rake TESTOPTS="--seed=7873"` works for me.

**Comment by ragesoss** [comment]
Ah, looks like a better fix is already prepared in an open PR, #370

**Comment by meowsus** [comment]
#370 has been merged
