### ISSUE TITLE
Error 500 Internal Server Error on  .MoveCssInline with AngleSharp > v0.9.11

### ISSUE THREAD

**Issue by possumdelight** [premailer/premailer#380]
Using VS 2019, updating NuGET package for AngleSharp breaks Premailer 2.01.

I've been running AngleSharp 0.9.11 for awhile now and Premailer 2.01 works well.  When I upgrade AngleSharp to anything past 0.9.11, it breaks premailer.

Specifically, I start getting internal server error 500 errors on any line of code that attempts to .MoveCssInline.

When I subsequently downgrade AngleSharp back to 0.9.11 it doesn't fix the problem, I have to restore from backup.

Any thoughts or suggestions?

Thanks!

Charlie

**Comment by tdegrunt** [comment]
Are you sure it's this Premailer? This is for the ruby package Premailer, which is at 1.11.1.

**Comment by possumdelight** [comment]
Premailer.net... thanks!
