### ISSUE TITLE
Push latest version to RubyGems

### ISSUE THREAD

**Issue by mscoutermarsh** [premailer/premailer#389]
Hello 👋,

We're currently using premailer master. Could we push the latest to RubyGems?

Thanks ❤️

**Comment by meowsus** [comment]
@alexdunae @akzhan Any reason not to release? If you'd like to give myself and @grosser  permissions to release to Ruby Gems either of us could handle this release for y'all.

**Comment by ricksuggs** [comment]
It would be great to use the new `drop_unmergeable_css_rules` option. Any timeline on releasing a new version of the gem?
https://github.com/premailer/premailer/commit/c1db3fb6f2decf81d7cb35f78351d005a4ba2dc7

**Comment by grosser** [comment]
try to hunt down a gem owner to do it or add new owner
https://rubygems.org/gems/premailer

**Comment by grosser** [comment]
1.12.0 🎉
