### ISSUE TITLE
The script removal has a greedy regex

### ISSUE THREAD

**Issue by romanbsd** [premailer/premailer#392]
Changed in this commit:
https://github.com/premailer/premailer/commit/e6ddc507102551a88fe37befa4d0c420d0ec10bc

Given the following input, it will delete all of it (not preserving the text "some text that should be preserved"):
```html
<script>
first script
</script>
some text that should be preserved.
<script>
second script
</script>
```
The regex should be non-greedy, e.g. ` /<script.*?\/script>/m`

**Comment by grosser** [comment]
thx!
fixed in https://github.com/premailer/premailer/pull/393
