### ISSUE TITLE
Nokogumbo has been merged into Nokogiri

### ISSUE THREAD

**Issue by dark-panda** [premailer/premailer#408]
Nokogumbo has been merged into Nokogiri, so an explicit `require` for `nokogumbo` is no longer required in the Nokogumbo adapter.

See https://github.com/sparklemotion/nokogiri/issues/2204 for details.

In my project, I removed the Nokogumbo gem from the Gemfile and got errors about not being able to find `nokogumbo.rb`. Adding an empty `nokogumbo.rb` file did the trick, but perhaps the explicit `require` should be removed from the adapter file?

**Comment by fukayatsu** [comment]
Done by #416 ?

**Comment by grosser** [comment]
looks like it, thx
