### ISSUE TITLE
Push latest version to RubyGems

### ISSUE THREAD

**Issue by shirts** [premailer/premailer#414]
👋  Hi @grosser 

I see commits to [`fix ruby 3 build`] (10/30/21) (https://github.com/premailer/premailer/commit/76db5662f8c32d923373e7d109b1bc9f977b48e2), but it looks like that code has not yet made it to [RubyGems](https://rubygems.org/gems/premailer) (last updated 5/13/21). Are there any plans to push the latest changes to RubyGems?

**Comment by grosser** [comment]
that's just changing CI setup and does not need to be released

**Comment by grosser** [comment]
thx, PR welcome
