### ISSUE TITLE
Please maintain changelog

### ISSUE THREAD

**Issue by johnnyshields** [premailer/premailer#428]
Premailer is on v1.20.0, but the last version to get a changelog entry is v1.17.0.

In addition, according to [Semver](https://semver.org/), please consider using tiny version releases if the fixes being released do not break any APIs or change functionality vs. expectation. ([The change in v1.20.0](https://github.com/premailer/premailer/compare/v1.19.0...v1.20.0) for example looks like it could have reasonably been released as v1.19.1.)

I use premailer for some pretty critical features in my app, so appreciate your help to make upgrades smooth 🙇‍♂️

**Comment by grosser** [comment]
Filled changelog and added PR template.

I'm using minor for new features and patches for fixes.
18 seems like a feature to me
19 is a bugfix so should have been patch
20 is somewhere in between but patch would have been fine
