### ISSUE TITLE
Two tests do not pass against Nokogiri >= 1.15.0

### ISSUE THREAD

**Issue by tagliala** [premailer/premailer#430]
```
  1) Failure:
TestPremailer#test_special_characters_nokogiri [~/dev/premailer/test/test_premailer.rb:10]:
--- expected
+++ actual
@@ -1 +1 @@
-"c&eacute;dille c&eacute; &amp; gar&ccedil;on gar&ccedil;on &agrave; &agrave; &nbsp; &amp; &copy;"
+"c&Atilde;&copy;dille c&eacute; &amp; gar&Atilde;&sect;on gar&ccedil;on &Atilde;&nbsp; &agrave; &nbsp; &amp; &copy;"


  2) Failure:
TestPremailer#test_special_characters_nokogiri_remote [~/dev/premailer/test/test_premailer.rb:16]:
--- expected
+++ actual
@@ -1 +1 @@
-"c&eacute;dille c&eacute; &amp; gar&ccedil;on gar&ccedil;on &agrave; &agrave; &nbsp; &amp; &copy;"
+"c&Atilde;&copy;dille c&eacute; &amp; gar&Atilde;&sect;on gar&ccedil;on &Atilde;&nbsp; &agrave; &nbsp; &amp; &copy;"


103 runs, 470 assertions, 2 failures, 0 errors, 0 skips

Focus on failing tests:
mtest test/test_premailer.rb:6
mtest test/test_premailer.rb:13
```

Bisected to: sparklemotion/nokogiri@0c05c1f7943ab99e653523b37298b2b551fa49e5, "dep: update libxml2 to v2.11.0 from v2.10.4"

Latest nokogiri main branch works with libxml v2.10.4

Unfortunately I do not have the resources to bisect libxml2

It looks like that `Ã©` is an improperly encoded version of `é` (like it is using ANSII encoding instead of UTF-8 somewhere), so I can't tell if this is an issue with premailer specs, premailer production code, or a regression in libxml2

**Comment by grosser** [comment]
I'd assume premailer specs sine otherwise someone would have complained by now.
https://github.com/premailer/premailer/pull/431 looks good ?

**Comment by tagliala** [comment]
> #431 looks good ?

`c&Atilde;&copy;dille` does not look good to me. I can't see how this can be rendered as `cédille` if it ends up in an email: https://tagliala.github.io/premailer.html

I will do other tests and let you know

**Comment by spiroid** [comment]
I also experimented an encoding issue while upgrading to nokogiri version higher than 1.15.0

Without further investigation, reading the changelog of nokogiri https://github.com/sparklemotion/nokogiri/releases/tag/v1.15.0, I noticed a change in the way the encoding information is passed:

> Encoding objects may now be passed to serialization methods like #to_xml, #to_html, #serialize, and #write_to to specify the output encoding. Previously only encoding names (strings) were accepted. [https://github.com/sparklemotion/nokogiri/issues/2774, https://github.com/sparklemotion/nokogiri/issues/2798] (Thanks, [@ellaklara](https://github.com/ellaklara)!)

Do you think it might be related ?

**Comment by tagliala** [comment]
Hello,

Sorry for the silence. I have some updates:

Let's say that I have an (utf-8 encoded) `test.html` file containing

```html
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title></title>
  </head>
  <body>
    <p>cédille</p>
  </body>
</html>
```

and the following test script

```rb
#!/usr/bin/env ruby

# frozen_string_literal: true

require 'premailer'

premailer = Premailer.new('test.html')

puts "Nokogiri #{Nokogiri::VERSION}\n#{premailer.to_inline_css}"
```

Here it is the output with two different Nokogiri versions:

```
Nokogiri 1.14.5
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title></title>
  </head>
  <body>
    <p>cédille</p>
  </body>
</html>

---

Nokogiri 1.15.4
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title></title>
  </head>
  <body>
    <p>cédille</p>
  </body>
</html>
```

However, if we remove the encoding meta tag from the HTML file

```html
<!doctype html>
<html lang="en">
  <head>
    <title></title>
  </head>
  <body>
    <p>cédille</p>
  </body>
</html>
```

The result is:

```
Nokogiri 1.14.5
<!DOCTYPE html>
<html lang="en">
  <head>
    <title></title>
  </head>
  <body>
    <p>c&eacute;dille</p>
  </body>
</html>

---

Nokogiri 1.15.4
<!DOCTYPE html>
<html lang="en">
  <head>
    <title></title>
  </head>
  <body>
    <p>c&Atilde;&copy;dille</p>
  </body>
</html>
```

So there has been a change in how Nokogiri works because to the underlying `libxml2` library

I can understand that libxml2 is now interpreting the html file without charset as US-ASCII, ignoring that the file is encoded in UTF-8. It may be an expected behavior, so the html string in specs should be fixed to include the proper content encoding

@spiroid do you have the meta tag in your email template?

**Comment by spiroid** [comment]
Hi @tagliala ,

Thanks for the feedback, interesting indeed !
We are not passing a complete html document as input but rather a raw html string, which means without any meta `Content-Type` set.

We are doing something like:

```
Premailer
      .new(raw_hteml_string, with_html_string: true, line_length: Float::INFINITY)
      .to_plain_text
```

I suppose without more context it is relying on a default encoding for the input.
If there is a change in the way `libxml2` treats the default encoding, it might explain our issue.

Looking closer at the document I see that there is an option on the premailer constructor to set encoding.
https://premailer.github.io/premailer/Premailer.html#initialize-instance_method

  - :input_encoding (String) — Manually specify the source documents encoding. This is a good idea. Default is ASCII-8BIT.
  - :output_encoding (String) — Output encoding option for Nokogiri adapter. Should be set to "US-ASCII" to output HTML entities instead of Unicode characters.

We will try to play with these and see what happens

**Comment by spiroid** [comment]
Follow up:

I can confirme it works if we set the input_encoding to 'UTF-8' for our use case.
I guess we won't be the only one that will be impacted by this default behaviour change :sweat_smile:

**Comment by tagliala** [comment]
> I guess we won't be the only one that will be impacted by this default behaviour change 😅

Do you know if an issue or a clarification should be asked in Nokogiri's repo? (even if this is related to libxml update, and if Nokogiri 1.15 is compiled against libxml2 2.10 it should work)

I couldn't find a meaningful libxml2 entry in the changelog for 2.11.0 related to this issue https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.11.0

**Comment by tagliala** [comment]
Created an issue at sparklemotion/nokogiri#2965

**Comment by grosser** [comment]
awesome issue, thx!

**Comment by grosser** [comment]
for now making the tests assert the wrong thing so we can update https://github.com/premailer/premailer/pull/441

**Comment by tagliala** [comment]
New failures against Nokogiri 1.16.0

```
  1) Failure:
TestPremailer#test_special_characters_nokogiri_remote [/Users/geremia/dev/premailer/test/test_premailer.rb:16]:
--- expected
+++ actual
@@ -1 +1,3 @@
-"c&Atilde;&copy;dille c&eacute; &amp; gar&Atilde;&sect;on gar&ccedil;on &Atilde;&nbsp; &agrave; &nbsp; &amp; &copy;"
+# encoding: ISO-8859-1
+#    valid: true
+"c\xC3\xA9dille c\xE9 &amp; gar\xC3\xA7on gar\xE7on \xC3\xA0 \xE0 \xA0 &amp; \xA9"


  2) Failure:
TestPremailer#test_special_characters_nokogiri [/Users/geremia/dev/premailer/test/test_premailer.rb:9]:
--- expected
+++ actual
@@ -1 +1,3 @@
-"c&Atilde;&copy;dille c&eacute; &amp; gar&Atilde;&sect;on gar&ccedil;on &Atilde;&nbsp; &agrave; &nbsp; &amp; &copy;"
+# encoding: ISO-8859-1
+#    valid: true
+"c\xC3\xA9dille c\xE9 &amp; gar\xC3\xA7on gar\xE7on \xC3\xA0 \xE0 \xA0 &amp; \xA9"
```

**Comment by grosser** [comment]
oh boy ... let add to the issue then and change them up again ...
also we'll need separate Gemfiles now or delete the Gemfile.lock on GHA

**Comment by tagliala** [comment]
So,

the problems with current specs are probably the following ones:

### `test_special_characters_nokogiri`

The `html` string being used is UTF-8, while it is assumed to be ISO-8859-1 in Nokogiri, causing the failure

```diff
diff --git a/test/test_premailer.rb b/test/test_premailer.rb
index 2dcb07f..07c5508 100644
--- a/test/test_premailer.rb
+++ b/test/test_premailer.rb
@@ -4,6 +4,7 @@ class TestPremailer < Premailer::TestCase
   # TODO: assertion is not correct see https://github.com/premailer/premailer/issues/430
   def test_special_characters_nokogiri
     html =     '<p>cédille c&eacute; & garçon gar&#231;on à &agrave; &nbsp; &amp; &copy;</p>'
+    raise html.encoding.to_s
```

```
  1) Error:
TestPremailer#test_special_characters_nokogiri:
RuntimeError: UTF-8
```

### `test_special_characters_nokogiri_remote`

The file being used is UTF-8 encoded, but nokogiri is assuming by default that it is ISO-8859-1, causing the problem

```
$ file -I test/files/chars.html 
test/files/chars.html: text/html; charset=utf-8
```


And probably

```
  # @option options [String] :output_encoding Output encoding option for Nokogiri adapter. Should be set to "US-ASCII" to output HTML entities instead of Unicode characters.
```

This is not the case anymore. Nokogiri seems to return escaped chars instead of HTML entities in most of the cases

**Comment by grosser** [comment]
can we somehow change nokogiris assumption ? (because I'd love to keep
things utf8)

**Comment by tagliala** [comment]
I'm trying something and let you know
