### ISSUE TITLE
Slow email generation and very high CPU

### ISSUE THREAD

**Issue by ldodds** [premailer/premailer#434]
Debugging some CPU spikes in our application when we are sending internal email reports, it appears that they are being caused by premailer.

Processing of the HTML file to inline the styles for the email take around 3-4 minutes for an email and results in ~100% CPU. The email consists of a large HTML table. The large the table, the slower the processing. 

The issue seems [very similar to this problem from 2017](https://github.com/premailer/premailer/pull/332) but as far as I can tell we are using the Nokogiri Fast adapter. We use the bootstrap-email gem which [explicitly sets that adapter](https://github.com/bootstrap-email/bootstrap-email/blob/1.1.5/lib/bootstrap-email/compiler.rb#L53).

Has anyone else seen this? Or any thoughts on workaround?

**Comment by grosser** [comment]
Try to see what part of premier is slow, if it's nokogiri then open the
issue there.
Best dump the email and then build a flame graph.

**Comment by ldodds** [comment]
I've realised that the optimisation added in 2017 only applies to a limit set of CSS styles. If [the style doesn't match a regex](https://github.com/premailer/premailer/blob/master/lib/premailer/adapter/nokogiri_fast.rb#L46), then there is a fallback to using nokogiri search.

Bootstrap has a lot of built in styles that don't match this, so `bootstrap-email` its not benefiting from the optimisation in a lot of cases, e.g:

```
.alert > tbody > tr > td
.row > table > tbody > tr > td
.text-left > tbody > tr > td

```

In an email which uses a large table, then this is triggered quite frequently, slowing down overall email generation. I'm not sure this is really a premailer problem, as nokogiri is ultimately responsible for the search, although there may be scope to improve the optimisation in other ways.

But wanted to note this in case someone else hit this problem either with `bootstrap-email` or if they're using custom styles.
