### ISSUE TITLE
Adapter::Nokogiri#to_inline_css raises ArgumentError with rule_set_exceptions: false

### ISSUE THREAD

**Issue by tommycrumrine** [premailer/premailer#436]
I'm still digging into this and definitely have limited knowledge here, so apologies if I'm misunderstanding something.

There's a form of invalid CSS that causes `Adapter::Nokogiri#to_inline_css` to raise `ArgumentError` for us even when passing the `rule_set_exceptions: false` flag. Here is a minimal reproduction:
```html
<html><head> <style type="text/css">
  * {
    margin:0px 0px 10px ! 0px;
  }
</style></head><body>
  <div style="margin:0px 0px 10px ! 0px;"></div>
</body></html>
```
This raises in the call to `CssParser.merge(declarations)` which is not rescued:
https://github.com/premailer/premailer/blob/0dbec96872d2a1440a2a4503f6fec92ceb8d0ab4/lib/premailer/adapter/nokogiri.rb#L75-L80

#435 has a failing test for this case.

**Comment by grosser** [comment]
should we move it down into the rescued block ?

**Comment by tommycrumrine** [comment]
> should we move it down into the rescued block ?

That was something I tried, but the method depend on the `merged` variable being set to a `‎CssParser::RuleSet` later on.

**Comment by tommycrumrine** [comment]
Or when we are building the `declarations` filter out the ones that are going to fail?

**Comment by grosser** [comment]
1.22.0

**Comment by tommycrumrine** [comment]
Appreciate the help here! 🎉
