### ISSUE TITLE
Newlines ignored when parsing HTML attributes

### ISSUE THREAD

**Issue by eflorit** [premailer/premailer#458]
It appears that Premailer skips attributes containing newlines when parsing HTML:

```ruby
# works as expected
Premailer.new("<span style=\"color:red\">TEST</span>", with_html_string: true).to_inline_css
=> "(...)<html><body><span style=\"color: red;\">TEST</span></body></html>\n"

# doesn't work as expected
Premailer.new("<span style=\"\ncolor:red\n\">TEST</span>", with_html_string: true).to_inline_css
=> "(...)<html><body><span style=\";\">TEST</span></body></html>\n"
```
Nokogiri natively does parse newlines correctly in attributes.

Do we agree this is a bug?

Tested with versions `1.26.0` and `1.8.7`

**Comment by grosser** [comment]
yeah that's bug

is this possibly related to https://github.com/premailer/css_parser/pull/166 ?
try with css_parser 1.17.1

**Comment by eflorit** [comment]
The PR you are referring to is a few days old, and this issue has been around for at least a few years (could be reproduced with a version of `css_parser` as old as `1.7.1`)

**Comment by grosser** [comment]
ah ok :)
PR welcome if you can find out how to fix

**Comment by eflorit** [comment]
@grosser: Feel free to review the above PR. I'm not familiar with all the processing done under the hood so I hope this fix doesn't have side effects, but it seems to fix the issue at least.

**Comment by grosser** [comment]
1.27.0
