### ISSUE TITLE
Do not encode HTML entities in URLs

### ISSUE THREAD

**Issue by refringe** [premailer/premailer#84]
This is the orignal link:
`<a href="http://testing.com/unsubscribe/?lang=en&email=">Unsubscribe</a>`

This is the current output:
`<a href="http://testing.com/unsubscribe/?lang=en&amp;email=">Unsubscribe</a>`

The ampersand, and all other HTML elements, are being encoded and they shouldn't be. I know this is best practice when it comes to websites, but it does not work in the professional email world.

Companies often use services like Thindata or Campaign Monitor to send mass emails out. When these services are used, links like the one above are replaced with tracking links. When these tracking links are clicked you are redirected using a server-side language to the original link. Because the server-side redirect doesn't decode HTML entities, like your browser or email client normally would, you are actually redirected to the encoded version of the link, which does not work.

Please stop doing _anything_ to links and leave the original as is.

_**Note:** this issue is identical to issue #14 which was fixed and closed. Perhaps a test should be added?_

**Comment by nolman** [comment]
I do not think ```escape_url_attributes: false``` actually fixes this bug, the bug is caused by using libxml2 (and xml escaping) to generate a html document.

**Comment by dstevenson** [comment]
Passing `escape_url_attributes: false` does not change escaping behavior for me at all

**Comment by theroch** [comment]
My previous version with (3.2.10.20170806-1) doesn't work correctly.
But with the current Nightly (3.2.10.20170830-1) the URLs are displayed correctly.
